name: Account Request Reject

on:
  issues:
    types:
      - labeled

jobs:
  # When ACCOUNT_REJECTED label is added to account management request
  request-rejected:
    if: github.event.label.name == 'ACCOUNT_REJECTED'
    runs-on: ubuntu-22.04
    permissions:
      issues: write
    steps:
      - name: Close rejected account request
        run: gh issue close "$NUMBER" --comment "$COMMENT" --reason "not planned"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          COMMENT: >
            Account management request REJECTED by Blossom Management.
            Closing request as "not planned".
