name: Create New Session

on:
  workflow_dispatch:

jobs:
  create-session:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ato/secops
            .sims
      
      - name: Create session
        run: |
          bash ato/secops/create_session.sh
